#ifndef __SIMERROR_H__
#define __SIMERROR_H__
#include <string>

namespace SimError
{
    // Exit function
    void Exit(int);

    // ================== Color codes for output formatting ====================
    const std::string  COLOR_RESET  = "\033[0m";
    const std::string  COLOR_RED    =  "\033[31m";      
    const std::string  COLOR_GREEN  =  "\033[32m";      
    const std::string  COLOR_YELLOW =  "\033[33m";

    /**
     * @brief Throws error generated in the std::cerr stream
     * 
     * @param er_code error code 
     * @param message error message
     * @param exit flag that tells weather to exit immediately
     */
    void throwError(std::string message, bool exit_flag = false);

    /**
     * @brief Throws warning generated by assembler in the std::cerr stream
     * 
     * @param wr_code warning code 
     * @param message Warning message
     */
    void throwWarning(std::string message);

    /**
     * @brief Displays a success message
     * 
     * @param message Success message
     */
    void throwSuccessMessage(std::string message, bool exit_flag = false);
};

#endif // __SIMERROR_H__