#include <iostream>
#include <string>

#include "SimError.h"

/**
 * @brief Throws error generated in the std::cerr stream
 * 
 * @param er_code error code 
 * @param message error message
 * @param exit flag that tells weather to exit immediately
 */
void SimError::throwError(std::string message, bool exit_flag)
{
    std::cerr << COLOR_RED <<"!ERROR: " << COLOR_RESET << message << std::endl;
    if(exit_flag)
    {
        SimError::Exit(EXIT_FAILURE);
    }
}

/**
 * @brief Throws warning generated by assembler in the std::cerr stream
 * 
 * @param wr_code warning code 
 * @param message Warning message
 */
void SimError::throwWarning(std::string message)
{
    std::cerr << COLOR_YELLOW <<"!WARNING: " << SimError::COLOR_RESET << message << std::endl;
}


/**
 * @brief Displays a success message
 * 
 * @param message Success message
 */
void SimError::throwSuccessMessage(std::string message, bool exit_flag)
{
    std::cout << COLOR_GREEN <<"SUCCESS : " << COLOR_RESET  << message <<std::endl;
    if(exit_flag)
    {
        SimError::Exit(EXIT_SUCCESS);
    }
}